import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { RecoilRoot } from "recoil";

export default function App({ Component, pageProps }: AppProps) {
  return (
    // RecoilRoot is a component that provides the Recoil state management context to your application.
    // It allows you to use Recoil's state management features, such as atoms and selectors, in your components.
    // By wrapping your application with RecoilRoot, you can manage global state in a more efficient and organized way.
    // This is particularly useful for managing complex state that needs to be shared across multiple components.
    // In this case, it is used to manage the state of the authentication modal.
    <RecoilRoot>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Component {...pageProps} />
    </RecoilRoot>
  );
}
